# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: action.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='action.proto',
  package='mahjongaction',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x61\x63tion.proto\x12\rmahjongaction\"\x97\x02\n\x06\x41\x63tion\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06\x64irect\x18\x02 \x01(\x05\x12\x36\n\x0b\x61\x63tion_type\x18\x03 \x01(\x0e\x32!.mahjongaction.Action.Action_type\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\t\"\x99\x01\n\x0b\x41\x63tion_type\x12\x0c\n\x08\x41\x43T_INIT\x10\x00\x12\r\n\tACT_READY\x10\x01\x12\x0b\n\x07\x41\x43T_GET\x10\x02\x12\x0c\n\x08\x41\x43T_POST\x10\x03\x12\x0b\n\x07\x41\x43T_EAT\x10\x04\x12\x0c\n\x08\x41\x43T_FOUR\x10\x05\x12\x0b\n\x07\x41\x43T_WIN\x10\x06\x12\x0e\n\nACT_ASSIGN\x10\x07\x12\x0c\n\x08\x41\x43T_DONE\x10\x08\x12\x0c\n\x08\x41\x43T_PASS\x10\tb\x06proto3')
)



_ACTION_ACTION_TYPE = _descriptor.EnumDescriptor(
  name='Action_type',
  full_name='mahjongaction.Action.Action_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACT_INIT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACT_READY', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACT_GET', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACT_POST', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACT_EAT', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACT_FOUR', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACT_WIN', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACT_ASSIGN', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACT_DONE', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACT_PASS', index=9, number=9,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=158,
  serialized_end=311,
)
_sym_db.RegisterEnumDescriptor(_ACTION_ACTION_TYPE)


_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='mahjongaction.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='mahjongaction.Action.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='direct', full_name='mahjongaction.Action.direct', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action_type', full_name='mahjongaction.Action.action_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='mahjongaction.Action.message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='mahjongaction.Action.data', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ACTION_ACTION_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=311,
)

_ACTION.fields_by_name['action_type'].enum_type = _ACTION_ACTION_TYPE
_ACTION_ACTION_TYPE.containing_type = _ACTION
DESCRIPTOR.message_types_by_name['Action'] = _ACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), dict(
  DESCRIPTOR = _ACTION,
  __module__ = 'action_pb2'
  # @@protoc_insertion_point(class_scope:mahjongaction.Action)
  ))
_sym_db.RegisterMessage(Action)


# @@protoc_insertion_point(module_scope)
